apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    name: vote-service
    app: vote-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: vote-app-pod
    app: vote-app