apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: result-app
spec:
  selector:
    matchLabels:
      name: result-app-pod
      type: front-end
  replicas: 1

  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: vote-app
        type: front-end
    spec:
      containers:
        - name: result-app-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
