apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deployment
  labels:
    name: vote-app-deployment
    app: vote-app
spec:
  selector:
    matchLabels:
      name: vote-app-pod
      type: front-end
  template:
    metadata:
      name: vote-app-pod
      labels:
        name: vote-app-pod
        type: front-end
        app: vote-app
    spec:
      containers:
        - name: vote-app-container
          image: dockersamples/vote
  replicas: 1
