apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: postgres-pod
    app: vote-app
spec:
  containers:
    - name: postgres-container
      image: postgres:9.4
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
      ports:
        - containerPort: 5432