apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis-pod
    app: vote-app
    type: caching-app
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379
