apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  labels:
    name: vote-app-pod
    type: front-end
    app: vote-app
spec:
  containers:
    - name: vote-app-container
      image: dockersamples/vote
      ports:
        - containerPort: 80