apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    type: back-end
    app: vote-app
spec:
  containers:
    - name: worker-app-container
      image: dockersamples/examplevotingapp_worker